[theme]
base = "dark"
primaryColor = "#D86B1F"
backgroundColor = "#090B13"
secondaryBackgroundColor = "#171421"
textColor = "#F8F9FA"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
